FROM eclipse-temurin:8
EXPOSE 8080
ADD C:/workspace/Prueba/test-jenkins-docker-integration/test-jenkins-docker-integration/targe/test-jenkins-docker-integration.jar test-jenkins-docker-integration.jar
ENTRYPOINT ["java","-jar","test-jenkins-docker-integration.jar"]